### ISSUE TITLE
TPA-LSTM only one input feature

### ISSUE THREAD

**Issue by Lucky7Chess** [jingw2/demand_forecast#10]
TPA-LSTM looks to only support one input feature.  Would you like me to update it to enable multiple features?  Seems important for a complete implementation unless I'm mistaken on the usage of your code.

**Comment by dolevelbaz** [comment]
@Lucky7Chess Do you know to add multiple features? I would appreciate such an addition.

**Comment by Kitaharakasusa** [comment]
> @Lucky7Chess Do you know to add multiple features? I would appreciate such an addition.

Have you solved the problem yet?
