### ISSUE TITLE
请问一下，为什么DeepAR中出来的sigma在softplus后要加1e-6

### ISSUE THREAD

**Issue by QuanhanSun** [jingw2/demand_forecast#17]

**Comment by jingw2** [comment]
也是怕等于0

**Comment by 2017wxyzwxyz** [comment]
@QuanhanSun ,请发给我一份你已经已经调通的基本代码，多谢！我的邮箱地址是NewWxy2016@163.com

**Comment by QuanhanSun** [comment]
我就直接pull下来就能跑，没改过东西

**Comment by QuanhanSun** [comment]
> @QuanhanSun ,请发给我一份你已经已经调通的基本代码，多谢！我的邮箱地址是[NewWxy2016@163.com](mailto:NewWxy2016@163.com)

我pull下来就能跑，没改过东西

**Comment by 2017wxyzwxyz** [comment]
请问你的torch版本是torch==1.1.0？

**Comment by QuanhanSun** [comment]
1.6.0

**Comment by QuanhanSun** [comment]
> 请问你的torch版本是torch==1.1.0？

1.6.0

**Comment by 2017wxyzwxyz** [comment]
谢谢答复！那你安装这个demand_forecast仓库项目代码是怎么安装的？

**Comment by QuanhanSun** [comment]
> 谢谢答复！那你安装这个demand_forecast仓库项目代码是怎么安装的？

我git clone下来就能跑，他依赖的环境都是很普遍用的包
