### ISSUE TITLE
Forking-Sequence in MQ-RNN

### ISSUE THREAD

**Issue by blablahaha** [jingw2/demand_forecast#3]
Hi,

Very nice project!

针对MQ-RNN，论文在「3.3. Training Scheme」这个章节，提到了「Forking-Sequence」的训练方法，但是代码中好像并木有相关的体现。

因此，想请问下，这部分是在哪里实现的呢？或者 我有什么遗漏的地方吗？

**Comment by jingw2** [comment]
这部分代码没有实现，只实现了简单版本
