### ISSUE TITLE
DeepAR里面为什么是对y进行embedding啊？

### ISSUE THREAD

**Issue by Pein-hub** [jingw2/demand_forecast#5]
论文里面好像是说对类别特征进行embedding，但是这里代码好像是把时序观察值进行了embedding？望大佬解答。
![image](https://user-images.githubusercontent.com/43956043/82037434-b4df7d00-96d4-11ea-86a7-c58a314161d5.png)
![image](https://user-images.githubusercontent.com/43956043/82037502-d04a8800-96d4-11ea-9ba3-60a4f55cfc39.png)

**Comment by jingw2** [comment]
我这边参考了Deep Factors里面Deep AR的实现方式，你也可以参考deep ar的方式
![image](https://user-images.githubusercontent.com/16906464/82991904-f8b97700-a030-11ea-9048-ba34a93b8e9b.png)
