### ISSUE TITLE
DeepAR模型训练LSTM层输入有问题？

### ISSUE THREAD

**Issue by Pein-hub** [jingw2/demand_forecast#6]
这里输入到lstm的样本inp维度是 (1,1,12)?  那相当于喂给lstm的步长就是1？ 那这不就是一个全连接网络了吗，没有用到RNN的特性啊。是不是有哪里搞错了 。 我参数都是按照readme里面输入的
![image](https://user-images.githubusercontent.com/43956043/82038431-1b18cf80-96d6-11ea-8dc5-28c498f26fdc.png)

**Comment by jingw2** [comment]
这里是一个个lstm cell向后，所有只有1个时间步。举个例子，你要一次性预测未来7天的。你要先预测未来1天的，然后用这天的最大似然估计作为预测第二天的输入。

**Comment by Pein-hub** [comment]
> 这里是一个个lstm cell向后，所有只有1个时间步。举个例子，你要一次性预测未来7天的。你要先预测未来1天的，然后用这天的最大似然估计作为预测第二天的输入。

但是你训练的时候输入给lstm-cell也是1步长的话，那你就没用上lstm循环的特性了吧。每次输入给lstm的都是1步长，感觉这样和一个全连接没什么区别。lstm最重要的就是可以用一段序列里面的历史信息，输入至少是一个序列才行？

**Comment by jingw2** [comment]
> > 这里是一个个lstm cell向后，所有只有1个时间步。举个例子，你要一次性预测未来7天的。你要先预测未来1天的，然后用这天的最大似然估计作为预测第二天的输入。
> 
> 
> 
> 但是你训练的时候输入给lstm-cell也是1步长的话，那你就没用上lstm循环的特性了吧。每次输入给lstm的都是1步长，感觉这样和一个全连接没什么区别。lstm最重要的就是可以用一段序列里面的历史信息，输入至少是一个序列才行？
> 
> 

这部分之前的encoder确实没有输入前面的hidden和cell的结果，现在更新了一下
