### ISSUE TITLE
AttributeError: module 'util' has no attribute 'batch_generator'

### ISSUE THREAD

**Issue by tomisalready** [jingw2/demand_forecast#9]
Traceback (most recent call last):                                            |
  File "tpa_lstm.py", line 249, in <module>
    losses, mape_list = train(X, y, args)
  File "tpa_lstm.py", line 145, in train
    Xtrain, ytrain, Xf, yf = util.batch_generator(Xtr, ytr, obs_len, seq_len, args.batch_size)
AttributeError: module 'util' has no attribute 'batch_generator'

**Comment by jingw2** [comment]
I update util.py to solve your problems, Please check again

**Comment by tomisalready** [comment]
thank you so much !!!
